# Question 1

In [1]:
#Importing the numpy package
import numpy as np
#Creating a numpy array
array = np.arange(2,51,3)
print(array)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# Question 2

In [3]:
#Creating 2 lists
list1 = []
list2 = []
#Accepting 5 elements in each list
#for list1
for i in range(5):
    x = int(input())
    list1.append(x)
print("List 1 :",list1)
#for list2
for i in range(5):
    y = int(input())
    list2.append(y)
print("List 2 :",list2)
#Converting both lists into numpy array
array1 = np.array(list1)
array2 = np.array(list2)
print("List 1 converted into array :",array1)
print("List 2 converted into array :",array2)
#Concatenate both the arrays
con = np.concatenate((array1,array2))
print("The concatenation of the two arrays is :",con)
#Sorting the arrays
sort = np.sort(con)
print("The sorted array is :", sort)

12
36
48
6
74
List 1 : [12, 36, 48, 6, 74]
63
11
39
4
69
List 2 : [63, 11, 39, 4, 69]
List 1 converted into array : [12 36 48  6 74]
List 2 converted into array : [63 11 39  4 69]
The concatenation of the two arrays is : [12 36 48  6 74 63 11 39  4 69]
The sorted array is : [ 4  6 11 12 36 39 48 63 69 74]


# Question 3

In [6]:
#Defining the array
array = np.array([[1,6,3],[4,9,8]])
print("The array is :",array)
#Finding the dimension of the array
print("The dimmension of array is :",array.ndim)
#Finding the size of the array
print("The size of array is :",array.size)

The array is : [[1 6 3]
 [4 9 8]]
The dimmension of array is : 2
The size of array is : 6


# Question 4

In [8]:
#Defining the array
array = np.arange(int(input()))
#Checking the shape of 1D array created
print("Shape of 1D array is:",array.shape)
#Converting 1D array into 2D array
array_row = array[np.newaxis]
print("The row of 2D array is :",array_row.shape)
array_col = array[:, np.newaxis]
print("The column of 2D array is :",array_col.shape)

6
Shape of 1D array is: (6,)
The row of 2D array is : (1, 6)
The column of 2D array is : (6, 1)


# Question 5

In [5]:
#Importing the numpy package
import numpy as np
#Creating square numpy arrays
a = np.array([[2,4],[3,6]])
b = np.array([[9,7],[8,1]])
#Vertical Stacking
print("Vertical Stacking :\n", np.vstack((a,b)))
#Horizontal Stacking
print("Horizontal Stacking :\n", np.hstack((a,b)))

Vertical Stacking :
 [[2 4]
 [3 6]
 [9 7]
 [8 1]]
Horizontal Stacking :
 [[2 4 9 7]
 [3 6 8 1]]


# Question 6

In [7]:
array = np.array([4,7,8,9,5,6,4,4])
unique, counts = np.unique(array, return_counts=True)
items = np.asarray((unique, counts)).T
print(items)

[[4 3]
 [5 1]
 [6 1]
 [7 1]
 [8 1]
 [9 1]]
